{{- if .Values.databaseSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgauth
data:
  password: {{ .Values.postgres.password | b64enc }}
  username: {{ .Values.postgres.username | b64enc }}
{{- end }}
